import type { Metadata } from "next";
import "./globals.css";
import Provider from "./components/Provider";
import Appbar from "./components/Appbar";
import { Toaster } from "@/components/ui/toaster"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-[#191414] text-white">
        <Provider>
          <Appbar/>
          { children }
        </Provider>
        <Toaster/>
      </body>
    </html>
  );
}
